CTA_TERMS = (
    "register",
    "sign up",
    "get started",
    "start now",
    "learn more",
    "more information",
    "continue",
    "apply now",
    "join now",
    "claim now",
    "begin",
    "registr",
    "comenzar",
    "empezar",
    "continuar",
    "siguiente",
    "mas informacion",
    "participar",
    "saiba mais",
    "cadastro",
    "inscreva",
    "devam",
    "basla",
)
CTA_EXCLUDES = (
    "deposit",
    "pay now",
    "checkout",
    "buy now",
    "download",
    "log in",
    "login",
    "shipping",
    "delivery",
    "privacy",
    "cookie",
    "terms and conditions",
    "customer service",
    "next page",
    "pagina siguiente",
    "page suivante",
)
