EXAMPLES = """\
Examples:
{"result":"relevant","reason":"The ad uses a public-figure confession hook to push users into a suspicious investment registration funnel.","advertiser":"Daily Finance News","product":"Investment lead-gen funnel","category":"make_money","grey_signals":["public-figure bait","fake-news style","registration funnel"],"language":"English"}
{"result":"relevant","reason":"The ad uses a fake breaking-news scandal about public funds and a finance minister on a throwaway tracking domain, which is a classic finance-scam prelander even though the final offer is hidden behind the click.","advertiser":"LiveNews","product":"Fake-news finance prelander","category":"other_relevant","grey_signals":["fake-news style","public-figure bait","public funds scandal","throwaway tracking domain"],"language":"Turkish"}
{"result":"relevant","reason":"The ad uses a Turkish politician/economic-news video with TL amounts, a registration CTA, and a random domain, matching the grey finance lead-gen pattern.","advertiser":"Turkiye Ekonomi Gundemi","product":"Finance lead-gen prelander","category":"other_relevant","grey_signals":["politician bait","TL amount claims","registration CTA","throwaway domain"],"language":"Turkish"}
{"result":"relevant","reason":"The ad uses a fake TV-news scandal about a public figure and a microphone/live-broadcast hook on a throwaway domain, which is a hidden-offer finance-scam prelander pattern.","advertiser":"24 news","product":"Fake-news finance prelander","category":"other_relevant","grey_signals":["fake-news style","public-figure bait","fake video creative","throwaway domain"],"language":"Turkish"}
{"result":"relevant","reason":"The ad uses Czech fake-news/public-figure bait about leaked truth, arrest or prison consequences, and a random lead-gen domain, matching a hidden finance-scam prelander.","advertiser":"Hotnews","product":"Fake-news finance prelander","category":"other_relevant","grey_signals":["fake-news style","public-figure bait","sensational scandal","throwaway domain"],"language":"Czech"}
{"result":"relevant","reason":"The ad promises monthly income from a vague crypto system on a throwaway domain.","advertiser":"Crypto Income 24","product":"Crypto income funnel","category":"crypto","grey_signals":["monthly income claim","vague offer","throwaway domain"],"language":"English"}
{"result":"relevant","reason":"The ad uses a Philippine public/business figure and Caticlan City app branding with a click-below CTA and mismatched lead-gen domain, matching a hidden finance-scam prelander pattern.","advertiser":"Philippine Update","product":"Fake government-app finance prelander","category":"other_relevant","grey_signals":["public-figure bait","government-app impersonation","registration CTA","mismatched domain"],"language":"English"}
{"result":"relevant","reason":"The ad uses a fake GMA/Fast Talk scandal with a Philippine governor or central-bank figure and a staged emergency on a throwaway domain, matching a hidden finance-scam prelander pattern.","advertiser":"Live TV Philippines","product":"Fake-TV finance prelander","category":"other_relevant","grey_signals":["fake-TV style","official/public-figure bait","sensational scandal","throwaway domain"],"language":"English"}
{"result":"not_relevant","reason":"The ad is for a normal forex broker and does not show scam, impersonation, fake-news, or exaggerated profit-funnel signals."}
{"result":"not_relevant","reason":"The ad is for a legitimate crypto exchange brand without grey/scam buyer-funnel signals."}
{"result":"not_relevant","reason":"The ad is a normal political news post from a consistent publisher/domain and does not show a suspicious redirect, throwaway lead-gen funnel, or hidden finance-scam prelander pattern."}
{"result":"not_relevant","reason":"The ad is an ordinary street-interview or emotional TV/person video with generic 'method', 'easy start', or registration wording; random domains and Facebook tracking alone are not enough without finance, bank/state, public-figure, or fake-news scandal evidence."}
{"result":"not_relevant","reason":"The ad is a prop trading funded-account discount/BOGO promotion, not a deceptive public-figure, fake-news, Telegram-signal, or guaranteed-profit scam funnel."}
{"result":"not_relevant","reason":"The ad is a normal branded stock-picking or portfolio research app and does not use fake-news impersonation, Telegram/signal lead-gen, or throwaway scam prelander tactics."}
{"result":"not_relevant","reason":"The ad is a generic AI webinar promising monthly income, but it is not specifically finance, crypto, forex, trading, yield, signal, broker-deposit, copy-trading, or fake-news finance-prelander related."}
{"result":"not_relevant","reason":"The ad is a generic make-money-online guide without a specific finance, crypto, forex, trading, yield, signal, broker-deposit, copy-trading, or fake-news finance-prelander hook."}
{"result":"not_relevant","reason":"The ad is for employee benefits/payment cards, not a grey consumer trading or investment funnel."}
{"result":"not_relevant","reason":"The ad is a Microsoft cloud-partner skilling campaign, not a grey finance or investment funnel."}
{"result":"not_relevant","reason":"The ad sells in-game currency or virtual items; gaming balance, bonds, and refunds are not finance-scam evidence."}
{"result":"not_relevant","reason":"The payment-app ad uses a standard mobile attribution deep link, which is not evidence of impersonation."}
{"result":"not_relevant","reason":"The ad is for a hotel booking offer, unrelated to finance, crypto, trading, or investment scams."}
{"result":"not_relevant","reason":"The ad is a gambling/casino/betting funnel without crypto, trading, yield, or investment messaging."}
{"result":"not_relevant","reason":"The ad is a deceptive health/nutra advertorial with hospital or news impersonation, but it does not reveal a finance, crypto, trading, or investment offer."}
{"result":"not_relevant","reason":"The ad is for a consistently branded forex education course and only promises learning or financial freedom, without fake-news bait, impersonation, guaranteed returns, or another scam-funnel signal."}
"""
