HARD_FINANCE_TERMS = (
    "crypto",
    "kripto",
    "bitcoin",
    "btc",
    "forex",
    "trading",
    "trade",
    "trader",
    "borsa",
    "broker",
    "mt4",
    "mt5",
    "staking",
    "yield",
    "copy-trading",
    "prop firm",
    "signal",
    "sinyal",
    "hisse",
    "yatırım",
)

GENERIC_AI_TERMS = (
    "ai",
    "artificial intelligence",
    "yapay zeka",
    "yapay zekâ",
    "chatgpt",
)

GENERIC_INCOME_TERMS = (
    "income",
    "monthly income",
    "earn",
    "earning",
    "make money",
    "online income",
    "kazanç",
    "kazanan",
    "kazanmak",
    "para kazan",
    "$",
    "finansal özgürlük",
    "financial freedom",
)

ALLOWED_RELEVANT_CATEGORIES = {
    "crypto",
    "forex",
    "trading",
    "broker",
    "investing",
    "yield",
    "make_money",
    "other_relevant",
}

RAW_SCAM_EVIDENCE_TERMS = (
    "fake news",
    "fake-news",
    "breaking news",
    "guaranteed profit",
    "guaranteed return",
    "unrealistic return",
    "minimum deposit",
    "secret system",
    "public funds",
    "government program",
    "impersonation",
)

STRONG_SCAM_EVIDENCE_TERMS = (
    "fake news",
    "fake-news",
    "fake tv",
    "fake-tv",
    "impersonation",
    "public-figure bait",
    "public figure bait",
    "government program",
    "guaranteed return",
    "guaranteed profit",
    "daily return",
    "high return",
    "unrealistic return",
    "minimum deposit",
    "passive income",
    "secret system",
    "throwaway domain",
    "mismatched domain",
)

SUPPORTING_ONLY_FUNNEL_TERMS = (
    "throwaway domain",
    "tracking",
    "facebook campaign",
    "registration",
    "register",
    "kaydol",
    "kayıt",
    "kolay başlangıç",
    "easy start",
    "method",
    "yöntem",
    "three months",
    "üç aydır",
)

FAKE_NEWS_FINANCE_PRELANDER_TERMS = (
    "breaking news",
    "fake news",
    "skandal",
    "scandal",
    "sensational",
    "ifşa",
    "bakan",
    "başkan",
    "minister",
    "politician",
    "political figure",
    "political event",
    "political bait",
    "parliament",
    "party logo",
    "chp",
    "anka",
    "police",
    "arrest",
    "şimşek",
    "mikrofon",
    "microphone",
    "truth revealed",
    "pravda",
    "uniklé",
    "česko",
    "cesko",
    "public funds",
    "halka ait",
    "stolen funds",
    "corruption",
    "yolsuzluk",
    "government",
    "devlet",
    "bank",
    "banka",
    "robbery",
    "theft",
    "soyğun",
    "soygun",
    "çald*",
    "cald*",
    "hakkım olan",
    "hakkim olan",
)

GUARD_HARD_FINANCE_TERMS = tuple(
    term for term in HARD_FINANCE_TERMS if term != "signal"
) + ("signal group", "trading signal", "telegram signal")

STRONG_TARGET_ANCHOR_TERMS = (
    *GUARD_HARD_FINANCE_TERMS,
    *FAKE_NEWS_FINANCE_PRELANDER_TERMS,
    "public figure",
    "famous person",
    "celebrity",
    "president",
    "prime minister",
    "tv presenter",
    "presenter",
    "journalist",
    "governor",
    "mayor",
    "central bank",
    "bangko sentral",
    "gma network",
    "fast talk",
    "boy abunda",
    "live tv sensation",
    "news studio",
    "tv-news",
    "banknote",
    "banknotes",
    "cash",
    "balance",
    "bakiye",
    "finans*",
    "investment opportunity",
    "investment opportunities",
    "tl",
    "₺",
    "tpao",
    "bsp",
    "caticlan city",
    "government app",
    "official app",
    "iş bankası",
    "is bankasi",
    "vakıf",
    "vakif",
    "ziraat",
    "atatürk",
    "ataturk",
    "şimşek",
    "simsek",
    "mansur",
    "sedat",
    "levent",
    "acun",
    "saliha",
)
